In [1]:

import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from collections import Counter

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.datasets import fetch_covtype

In [2]:

os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'  # Suppresses INFO and WARNING messages

import tensorflow as tf

from tensorflow import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,Input
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.optimizers.schedules import CosineDecay

random_seed = 42

tf.random.set_seed(random_seed)

In [3]:
from tensorflow.python.client import device_lib
print(device_lib.list_local_devices())
print(tf.config.list_physical_devices('GPU'))

[name: "/device:CPU:0"
device_type: "CPU"
memory_limit: 268435456
locality {
}
incarnation: 14366927823928084099
xla_global_id: -1
, name: "/device:GPU:0"
device_type: "GPU"
memory_limit: 6365904896
locality {
  bus_id: 1
  links {
  }
}
incarnation: 1274001069584333427
physical_device_desc: "device: 0, name: NVIDIA GeForce RTX 2070 SUPER, pci bus id: 0000:01:00.0, compute capability: 7.5"
xla_global_id: 416903419
]
[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

----

In [4]:
import pickle 

with open(r"hw2_x.pkl", 'rb') as f:
    X_sub = pickle.load(f)

with open(r"hw2_y.pkl", 'rb') as f:
    y_sub = pickle.load(f)

In [8]:
pd.crosstab(y_sub, columns='count')

col_0  count
row_0
0       2747
1       2747
2       2747
3       2747
4       2747
5       2747
6       2747

## part 1a

In [10]:
X_train, X_test, y_train, y_test = train_test_split(
                            X_sub,
                            y_sub,
                            test_size = 0.2,
                            random_state = random_seed,
                            stratify = y_sub
)

stdscale = StandardScaler()
X_train = stdscale.fit_transform(X_train)
X_test = stdscale.transform(X_test)

In [11]:
n_features = X_train.shape[1]
print("num col: ", n_features)

n_classes = len(np.unique(y_train))
print("num class target: ", n_classes)


model1 = keras.models.Sequential(
    [
        keras.layers.Input(shape=(n_features, )), 
        keras.layers.Dense(32,  activation = "relu"),
        keras.layers.Dense(16,  activation = "relu"),
        keras.layers.Dense(n_classes,   activation = "softmax"),
    ]
)

num col:  54
num class target:  7

In [12]:
optimizer1 = Adam(learning_rate= 0.0001)
loss1 = 'sparse_categorical_crossentropy'
metric1 = ['accuracy']

model1.compile(optimizer= optimizer1, loss= loss1, metrics= metric1) 

#---------------
n_epoch = 20
batch1 = 32


model1_history = model1.fit(
        X_train, y_train,
        epochs = n_epoch,
        # class_weight = ..,
        batch_size = batch1,
        verbose = 1
)

print(model1_history.history['accuracy'][-1])

Epoch 1/20
481/481 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - accuracy: 0.2483 - loss: 1.8671
Epoch 2/20
481/481 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.4521 - loss: 1.5884
Epoch 3/20
481/481 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.5448 - loss: 1.3431
Epoch 4/20
481/481 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.5678 - loss: 1.1551
Epoch 5/20
481/481 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.5887 - loss: 1.0427
Epoch 6/20
481/481 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.6063 - loss: 0.9759
Epoch 7/20
481/481 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.6202 - loss: 0.9320
Epoch 8/20
481/481 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.6302 - loss: 0.9004
Epoch 9/20
481/481 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.6386 - loss: 0.8762
Epoch 10/20
481/481 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.6466 - loss: 0.8566
Epoch 11/20
481/481 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.6523 - loss: 0.8399
Epoch 12/20
481/481 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.6560 - loss: 0.8251
Epoch 13/20
481/481 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.6600 - loss: 0.8120
Epoch 14/20
481/481 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.6658 - loss: 0.8001
Epoch 15/20
481/481 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.6709 - loss: 0.7891
Epoch 16/20
481/481 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.6776 - loss: 0.7789
Epoch 17/20
481/481 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.6835 - loss: 0.7693
Epoch 18/20
481/481 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.6899 - loss: 0.7602
Epoch 19/20
481/481 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.6944 - loss: 0.7515
Epoch 20/20
481/481 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.6996 - loss: 0.7434
0.6996034383773804

---
# p2

In [15]:
# model2 = keras.models.Sequential(
#     [
#         keras.layers.Input(shape=(n_features, )), 
#         keras.layers.Dense(32,  activation = "relu"),
#         keras.layers.Dense(16,  activation = "relu"),
#         keras.layers.Dense(n_classes,   activation = "softmax"),
#     ]
# )

# optimizer2 = Adam(learning_rate= 0.0001)
# loss2 = 'sparse_categorical_crossentropy'
# metric2 = ['accuracy']

# model2.compile(optimizer= optimizer2, loss= loss2, metrics= metric2) 

# #---------------
# n_epoch = 20
# batch_set1 = [4, 8 ]# , 16, 128]

# p2_compile_loss = []
# p2_compile_accuracy = []


# for b in batch_set1:

#     model2_history = model2.fit(
#             X_train, y_train,
#             epochs = n_epoch,
#             batch_size = b,
#             verbose = 0
#     )
#     p2_compile_accuracy.append(model2_history.history['accuracy'][-1])
#     p2_compile_loss.append(model2_history.history['loss'][-1])


# p2_comparison_table = pd.DataFrame({
#     'batch_size': batch_set1,
#     'accuracy_result': p2_compile_accuracy,
#     'loss_result': p2_compile_loss
# })

# display(p2_comparison_table)
# # print(p2_comparison_table.query(ma))

   batch_size  accuracy_result  loss_result
0           4         0.743353     0.617119
1           8         0.762465     0.565945

In [21]:
# p2_comparison_table.loc[p2_comparison_table['accuracy_result'].idxmax(), 'batch_size']

np.int64(8)

In [ ]:
from keras import layers

def p1_model(lr):
    model = keras.Sequential([
            layers.Input(shape= (n_features,)),
            layers.Dense(32,    activation="relu"),
            layers.Dense(16,    activation="relu"),
            layers.Dense(n_classes, activation="softmax")
        ])

    model.compile(
        optimizer =     Adam(learning_rate= lr),
        loss =          "sparse_categorical_crossentropy",
        metrics =       ['accuracy']
    )

    return model


n_epoch = 20
batch_set1 = [4, 8 ]# , 16, 128]

p2_results = []

for b in batch_set1:
    keras.backend.clear_session()
    model  = p1_model(1e-4)
    history = model.fit(
            X_train, y_train,
            epochs = n_epoch,
            batch_size = b,
            verbose = 0
    )
    p2_results.append({
        "type": 'batch sizes',
        "value": b,
        "accuracy": history.history["accuracy"][-1],
        "loss": history.history["loss"][-1]
    })

p2 = pd.DataFrame(p2_results)
display(p2)

---

# p3

In [24]:
from keras import layers

In [22]:

def p1_model(lr):
    model = keras.Sequential([
        layers.Input(shape=(n_features,)),
        layers.Dense(32, activation="relu"),
        layers.Dense(16, activation="relu"),
        layers.Dense(n_classes, activation="softmax")
    ])

    model.compile(
        optimizer=Adam(learning_rate=lr),
        loss="sparse_categorical_crossentropy",
        metrics=["accuracy"]
    )
    return model

In [27]:
p3_lr = [1e-3, 5e-4, 1e-4,5e-5, 1e-5]

def p3_run(lr_list):
    learning_rate_experiment = lr_list 
    n_ep = 20
    batch = 32

    results = []

    for lr in learning_rate_experiment:
        keras.backend.clear_session()
        model  = p1_model(lr)
        history = model.fit(
                X_train, y_train,
                epochs = n_ep,
                batch_size = batch,
                verbose = 0
        )
        results.append({
            "type": 'optimizer learning rate',
            "value": lr,
            "accuracy": history.history["accuracy"][-1],
            "loss": history.history["loss"][-1]
        })

    return pd.DataFrame(results)

def p1_model(lr):
    model = keras.Sequential([
        layers.Input(shape=(n_features,)),
        layers.Dense(32, activation="relu"),
        layers.Dense(16, activation="relu"),
        layers.Dense(n_classes, activation="softmax")
    ])

    model.compile(
        optimizer=Adam(learning_rate=lr),
        loss="sparse_categorical_crossentropy",
        metrics=["accuracy"]
    )
    return model

p3 = p3_run(p3_lr)

display(p3)
print(p3.loc[p3['accuracy'].idxmax(), 'value'])

                      type   value  accuracy      loss
0  optimizer learning rate  0.0010  0.755379  0.577657
1  optimizer learning rate  0.0005  0.734252  0.642202

0.001

---

# p4

In [ ]:
batch_size = 32
n_epoch = 20




init_lr = [1e-2, 5e-3, 1e-3,5e-4, 1e-4]

def p4_run(lr):
    results = []

    for l in lr:
        keras.backend.clear_session()
        steps_per_epoch = int(np.ceil(len(X_train) / batch_size))
        total_steps = n_epoch * steps_per_epoch
        lr_schedule = CosineDecay(
                initial_learning_rate= l,
                decay_steps=total_steps,
                alpha=0.0  # Final LR = 0
            )

        model  = p1_model(lr_schedule)
        history = model.fit(
                X_train, y_train,
                epochs = n_epoch,
                batch_size = batch_size,
                verbose = 0
        )
        results.append({
            "type": 'Cosine decay LR',
            "value": l,
            "accuracy": history.history["accuracy"][-1],
            "loss": history.history["loss"][-1]
        })

    return pd.DataFrame(results)


p4 = p4_run(init_lr) 
display(p4)
print(p4.loc[p4['accuracy'].idxmax(), 'value'])

---
# p5

In [ ]:
p1 =pd.DataFrame({
    "type": 'baseline',
    "value": "",
    "accuracy": model1_history.history['accuracy'][-1],
    "loss": model1_history.history["loss"][-1]
            })

compare_all = pd.concat([p1, p2, p3, p4], ignore_index=True)

display(compare_all.sort_values('accuracy', ascending=False))